### ISSUE TITLE
gulp sass globbing

### ISSUE THREAD

**Issue by dewwwald** [larrybotha/styleguide#8]
Hey Larry,

There are other ways to go about this, like installing a ruby plugin called sass-globbing. However this is also another cool solution I came across.

https://www.npmjs.com/package/gulp-sass-glob

Now no more _!all.scss and opening multiple files to add a single file. Simply use * where you would have all.

Let me know what you think.

Kind regards,
Dewald.

**Comment by larrybotha** [comment]
I wouldn't use a Ruby gem for task automation relying on Node.

Interesting, it'll definitely reduce overhead in adding and managing files, but also adds a dependency on being able to use the framework.

May be better suited to being added to specific projects, rather than here. Adding it here decreases the adoptability of the framework. I'll probably add it to tasks on our boilerplates, though.

Thanks @dewwwald.

**Comment by dewwwald** [comment]
@larrybotha Makes sense. Thanks! I also thought of the issue where you need files to be excludable from the framework, this does not seem to be supported yet. 

I must agree that going with this solution does break some of the framework features.

But now I was thinking of a task that automatically adds the new file to _!all if it is not there. That way you can leave it commented out or in the order you like it. This will only reduce typing when adding components. I'll do some reading on this.
